---
- hosts: all
  become: true
  tasks:
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
        force: yes
        update_cache: yes
    - name: add skype repo key
      apt_key:
        url: https://repo.skype.com/data/SKYPE-GPG-KEY
    - name: add neofetch key
      apt_key:
        url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
    - name: add apt repos
      apt_repository:
        repo: "{{ item }}"
        state: present
     with_items:
        - deb [arch=amd64] https://repo.skype.com/deb stable main
        - deb http://us.archive.ubuntu.com/ubuntu/ zesty multiverse
        - deb http://us.archive.ubuntu.com/ubuntu/ zesty-updates multiverse
        - deb http://dl.binary.com/dawidd6/neofetch jessie main
    - name: install skype
      apt:
        name: skypeforlinux
    - name: install packages on Debian/Ubuntu
      apt:
        name: "{{ item }}"
        state: present
        force: yes
        update_cache: yes
      with_items:
        - curl
        - gcc
        - git
        - g++
        - neofetch
        - python
        - python-all
        - python-all-dev
        - python-dev
        - python-pip
        - rofi
        - scrot
        - unzip
        - vlc
        - vim
        - zip
        # for keypass
        - gtbase5-dev
        - libqt5x11extras5-dev
        - qttools5-dev
        - qttools5-dev-tools
        - libgcrypt20-dev
        - zlib1g-dev
        - libxi-dev
        - libxtst-dev
        - xbindkeys
